### ISSUE TITLE
Put together 1/20th field

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/DeepSpace-2019#158]
See Schmidt for parts

**Comment by Eiim** [comment]
Manav knows the most about the 1/20th scale field, I'm adding him

**Comment by Eiim** [comment]
Everything but the field perimeter and player station area is done and glued, the perimeter isn't glued down due to issues with the connectors. Thanks to @LillianMcGee and @Sam-King4611 for gluing stuff down.

In terms of the connectors, toothpicks or raw spaghetti might work better. The issue right now is that the filament we used has a curve. If we can't make something that works better, we'll work with it.
