### ISSUE TITLE
Cargo Bay Side (single)

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#48]

**Comment by olentangyfrcowner** [comment]
https://firstfrc.blob.core.windows.net/frc2019/DrawingPackages/LayoutandMarkingDiagram.pdf

PDF file to help build.

**Comment by olentangyfrcowner** [comment]
Did this get finished after the meeting ended?

**Comment by priyankaagochiya** [comment]
Not all the way. We still need to add the top and the hatch. Should not take much time at all today since the parts have already been cut out last night. 





On Saturday, January 12, 2019, 7:02 AM, olentangyfrcowner <notifications@github.com> wrote:


Did this get finished after the meeting ended?

**Comment by sethstobart** [comment]
Has the velcro and retroreflective been placed? @priyankaagochiya @benschwartz9
